<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pulse_schedule"/>
        <xs:element ref="input_start"/>
        <xs:element ref="output"/>
        <xs:element ref="input_transp"/>
        <xs:element ref="time_stop"/>
        <xs:element ref="time_ext"/>
        <xs:element ref="controller"/>
        <xs:element ref="step_max"/>
        <xs:element ref="use_astra"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pulse_schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="user"/>
        <xs:element ref="database"/>
        <xs:element ref="pulse"/>
        <xs:element ref="run"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="input_start">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="user"/>
        <xs:element ref="database"/>
        <xs:element ref="pulse"/>
        <xs:element ref="run"/>
        <xs:element ref="time_start"/>
        <xs:element ref="interp_mode"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="time_start" type="xs:decimal"/>
  <xs:element name="output">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="database"/>
        <xs:element ref="pulse"/>
        <xs:element ref="run"/>
        <xs:element ref="decimation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="decimation" type="xs:integer"/>
  <xs:element name="input_transp">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="database"/>
        <xs:element ref="pulse"/>
        <xs:element ref="run"/>
        <xs:element ref="interp_mode"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="time_stop" type="xs:decimal"/>
  <xs:element name="time_ext" type="xs:double"/>
  <xs:element name="controller" type="xs:NCName"/>
  <xs:element name="step_max" type="xs:integer"/>
  <xs:element name="use_astra" type="xs:integer"/>
  <xs:element name="user">
    <xs:complexType/>
  </xs:element>
  <xs:element name="database" type="xs:NCName"/>
  <xs:element name="pulse" type="xs:integer"/>
  <xs:element name="run" type="xs:integer"/>
  <xs:element name="interp_mode" type="xs:integer"/>
</xs:schema>
