/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Jan  4 10:38:12 2019
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include<stdio.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void read_tt_kavin2_Outputs_wrapper(real_T *y0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
int i,k; static int kl;
double y[6];
FILE*f;char b[256];

if(kl==0){

f=fopen("tt_kavin2.dat","r");fgets(b,255,f);
fscanf(f,"%lf ",&y[0]); y[0]=y[0]*1e-3; fgets(b,255,f);
//for(i=1;i<4;i++){ fscanf(f,"%lf %lf %lf",&y[i],&y[i]+1,&y[i]+2);
//mexPrintf(" i pf_val0 pf_valn %d  %g  %g  %g \n ",
//		  i,y[i],y[i+1],y[i+2]);}
for(i=1;i<4;i++) fscanf(f,"%lf ",&y[i]);
//mexPrintf(" i y %d  %g  \n ",
//		  i,y[i]);}

y0[0]=y[0];y0[1]=y[2];y0[2]=y[3];y0[3]=y[1]; fgets(b,255,f);
fscanf(f,"%lf %lf",&y[4],&y[5]);
//mexPrintf(" y4  y5  %g  %g \n ",y[4],y[5]);
y0[4]=y[4];y0[5]=y[5];
fclose(f);

kl=1;}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
