      real *8 n_e,n_e0,n_i,n_i0,n_d,n_d0,n0,n00,I_p,I_r,n_tot,n_tot0,
     *  L_p,I_p0
    	common
     */c_break1/n_e,n_e0,n_d,n_d0,n0,n00,T_e,T_e0,T_i,T_i0
     */c_break2/a_min,R_maj,n_i,n_i0
     */c_break3/I_p,I_p0,P_ioniz,P_cx,P_rad,P_ech
     */c_break4/z_eff,v_v0,v_p
     */c_break5/v_n,p_lambda,r_pl0,v_v00,q_ech,tay_ee
     */c_break6/v_p0
     */c_break7/g_v,g_v0





















   



