!      REAL L31, L32, L34, ALFA
!      REAL ft
!      REAL Zeff, nuestar, nuistar

      REAL *8 L31, L32, L34, ALFA
      REAL *8 ft
      REAL *8 Zeff, nuestar, nuistar
!

!      REAL ZZ, znuestar, znuistar, zsqnuest, zeffp1, zsqnui, znui2ft6
!      REAL zft31eff, zft32ee_eff, zft32ei_eff, zft34eff, zalfa0

      REAL *8 ZZ, znuestar, znuistar, zsqnuest, zeffp1, zsqnui, znui2ft6
      REAL *8 zft31eff, zft32ee_eff, zft32ei_eff, zft34eff, zalfa0
!-----------------------------------------------------------------------



