
c-------  Common Blocks for divertor

	parameter ( npo1=2)

	common
     *  /c_nrad/n_rad

     *  /c_div7/den(npo),den0(npo),sden(nimp,npo)

     *  /c_div25/
     *  den_imp(nimp,nimp,npo1),den0_imp(nimp,nimp,npo1),
     *  n_imp(nimp)

     *  /c_div30/
     *  den_imp_n(nimp,npo1),den0_imp_n(nimp,npo1),
     *  den_neut(npo),den0_neut(npo)

     *  /c_div34/z_imp(nimp),n_imp_tot
     *  /c_div35/den_imp_tot(nimp)


















