# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1598, 1102)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInput = QtWidgets.QWidget()
        self.tabInput.setObjectName("tabInput")
        self.tabWidgetInput = QtWidgets.QTabWidget(self.tabInput)
        self.tabWidgetInput.setGeometry(QtCore.QRect(10, 380, 1421, 541))
        self.tabWidgetInput.setObjectName("tabWidgetInput")
        self.tabControlData = QtWidgets.QWidget()
        self.tabControlData.setObjectName("tabControlData")
        self.tabWidgetInput.addTab(self.tabControlData, "")
        self.tabExternalData = QtWidgets.QWidget()
        self.tabExternalData.setObjectName("tabExternalData")
        self.tabWidgetInput.addTab(self.tabExternalData, "")
        self.tabGeneralData = QtWidgets.QWidget()
        self.tabGeneralData.setObjectName("tabGeneralData")
        self.tabWidgetInput.addTab(self.tabGeneralData, "")
        self.tabDINAData = QtWidgets.QWidget()
        self.tabDINAData.setObjectName("tabDINAData")
        self.tabWidgetInput.addTab(self.tabDINAData, "")
        self.tabTokamakData = QtWidgets.QWidget()
        self.tabTokamakData.setObjectName("tabTokamakData")
        self.tabWidgetInput.addTab(self.tabTokamakData, "")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tabInput)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 591, 351))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layoutInputSetup = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layoutInputSetup.setContentsMargins(0, 0, 0, 0)
        self.layoutInputSetup.setObjectName("layoutInputSetup")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelInputPulse = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelInputPulse.setObjectName("labelInputPulse")
        self.gridLayout.addWidget(self.labelInputPulse, 0, 0, 1, 1)
        self.lineInputRun = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineInputRun.setObjectName("lineInputRun")
        self.gridLayout.addWidget(self.lineInputRun, 1, 1, 1, 1)
        self.lineInputPulse = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineInputPulse.setObjectName("lineInputPulse")
        self.gridLayout.addWidget(self.lineInputPulse, 0, 1, 1, 1)
        self.labelInputRun = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelInputRun.setObjectName("labelInputRun")
        self.gridLayout.addWidget(self.labelInputRun, 1, 0, 1, 1)
        self.labelInputTokamak = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelInputTokamak.setObjectName("labelInputTokamak")
        self.gridLayout.addWidget(self.labelInputTokamak, 2, 0, 1, 1)
        self.lineInputTokamak = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineInputTokamak.setObjectName("lineInputTokamak")
        self.gridLayout.addWidget(self.lineInputTokamak, 2, 1, 1, 1)
        self.layoutInputSetup.addLayout(self.gridLayout, 10, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnSave.setObjectName("btnSave")
        self.layoutInputSetup.addWidget(self.btnSave, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layoutInputSetup.addWidget(self.label_2, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutInputSetup.addWidget(self.label, 5, 0, 1, 1)
        self.btnLoad = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnLoad.setObjectName("btnLoad")
        self.layoutInputSetup.addWidget(self.btnLoad, 4, 0, 1, 1)
        self.labelDirSave = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelDirSave.setObjectName("labelDirSave")
        self.layoutInputSetup.addWidget(self.labelDirSave, 7, 0, 1, 1)
        self.labelDirLoad = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelDirLoad.setObjectName("labelDirLoad")
        self.layoutInputSetup.addWidget(self.labelDirLoad, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabInput, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabOutput)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 100, 200))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textUser = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.textUser.setObjectName("textUser")
        self.gridLayout_2.addWidget(self.textUser, 3, 1, 1, 1)
        self.btnLoadIDS = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnLoadIDS.setObjectName("btnLoadIDS")
        self.gridLayout_2.addWidget(self.btnLoadIDS, 5, 1, 1, 1)
        self.labelRun = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelRun.setObjectName("labelRun")
        self.gridLayout_2.addWidget(self.labelRun, 1, 0, 1, 1)
        self.labelPulse = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelPulse.setObjectName("labelPulse")
        self.gridLayout_2.addWidget(self.labelPulse, 0, 0, 1, 1)
        self.textPulse = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textPulse.setObjectName("textPulse")
        self.gridLayout_2.addWidget(self.textPulse, 0, 1, 1, 1)
        self.textRun = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.textRun.setObjectName("textRun")
        self.gridLayout_2.addWidget(self.textRun, 1, 1, 1, 1)
        self.labelIDSInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelIDSInfo.setText("")
        self.labelIDSInfo.setObjectName("labelIDSInfo")
        self.gridLayout_2.addWidget(self.labelIDSInfo, 5, 0, 1, 1)
        self.textBase = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.textBase.setObjectName("textBase")
        self.gridLayout_2.addWidget(self.textBase, 2, 1, 1, 1)
        self.labelBase = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelBase.setObjectName("labelBase")
        self.gridLayout_2.addWidget(self.labelBase, 2, 0, 1, 1)
        self.labelUser = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelUser.setObjectName("labelUser")
        self.gridLayout_2.addWidget(self.labelUser, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabOutput, "")
        self.tabVIZ = QtWidgets.QWidget()
        self.tabVIZ.setObjectName("tabVIZ")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabVIZ)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1571, 1011))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.tabVIZ, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1598, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidgetInput.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DINA"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabControlData), _translate("MainWindow", "Controller Data"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabExternalData), _translate("MainWindow", "External Data"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabGeneralData), _translate("MainWindow", "General Data"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabDINAData), _translate("MainWindow", "DINA Data"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabTokamakData), _translate("MainWindow", "Tokamak Data"))
        self.labelInputPulse.setText(_translate("MainWindow", "Pulse"))
        self.labelInputRun.setText(_translate("MainWindow", "Run"))
        self.labelInputTokamak.setText(_translate("MainWindow", "Tokamak"))
        self.btnSave.setText(_translate("MainWindow", "Save to work directory"))
        self.btnLoad.setText(_translate("MainWindow", "Load setups"))
        self.labelDirSave.setText(_translate("MainWindow", "Select DINA work directory"))
        self.labelDirLoad.setText(_translate("MainWindow", "Select setups source folder"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInput), _translate("MainWindow", "Input"))
        self.btnLoadIDS.setText(_translate("MainWindow", "Load IDS"))
        self.labelRun.setText(_translate("MainWindow", "Run"))
        self.labelPulse.setText(_translate("MainWindow", "Pulse"))
        self.labelBase.setText(_translate("MainWindow", "Database"))
        self.labelUser.setText(_translate("MainWindow", "User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVIZ), _translate("MainWindow", "VIZ"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

