# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1624, 1087)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInput = QtWidgets.QWidget()
        self.tabInput.setObjectName("tabInput")
        self.tabWidgetInput = QtWidgets.QTabWidget(self.tabInput)
        self.tabWidgetInput.setGeometry(QtCore.QRect(10, 200, 1551, 741))
        self.tabWidgetInput.setObjectName("tabWidgetInput")
        self.tabCurrents = QtWidgets.QWidget()
        self.tabCurrents.setObjectName("tabCurrents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabCurrents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableCurrents = QtWidgets.QTableWidget(self.tabCurrents)
        self.tableCurrents.setDragEnabled(False)
        self.tableCurrents.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableCurrents.setRowCount(15)
        self.tableCurrents.setColumnCount(13)
        self.tableCurrents.setObjectName("tableCurrents")
        self.verticalLayout_2.addWidget(self.tableCurrents)
        self.tabWidgetInput.addTab(self.tabCurrents, "")
        self.tabVoltages = QtWidgets.QWidget()
        self.tabVoltages.setObjectName("tabVoltages")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabVoltages)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableVoltages = QtWidgets.QTableWidget(self.tabVoltages)
        self.tableVoltages.setDragEnabled(False)
        self.tableVoltages.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableVoltages.setRowCount(15)
        self.tableVoltages.setColumnCount(12)
        self.tableVoltages.setObjectName("tableVoltages")
        self.verticalLayout_3.addWidget(self.tableVoltages)
        self.tabWidgetInput.addTab(self.tabVoltages, "")
        self.tabGaps = QtWidgets.QWidget()
        self.tabGaps.setObjectName("tabGaps")
        self.tableGap1 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap1.setGeometry(QtCore.QRect(20, 60, 171, 201))
        self.tableGap1.setDragEnabled(False)
        self.tableGap1.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap1.setRowCount(6)
        self.tableGap1.setColumnCount(2)
        self.tableGap1.setObjectName("tableGap1")
        self.tableGap2 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap2.setGeometry(QtCore.QRect(200, 60, 171, 201))
        self.tableGap2.setDragEnabled(False)
        self.tableGap2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap2.setRowCount(6)
        self.tableGap2.setColumnCount(2)
        self.tableGap2.setObjectName("tableGap2")
        self.tableGap3 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap3.setGeometry(QtCore.QRect(390, 60, 171, 201))
        self.tableGap3.setDragEnabled(False)
        self.tableGap3.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap3.setRowCount(6)
        self.tableGap3.setColumnCount(2)
        self.tableGap3.setObjectName("tableGap3")
        self.tableGap4 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap4.setGeometry(QtCore.QRect(580, 60, 171, 201))
        self.tableGap4.setDragEnabled(False)
        self.tableGap4.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap4.setRowCount(6)
        self.tableGap4.setColumnCount(2)
        self.tableGap4.setObjectName("tableGap4")
        self.tableGap5 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap5.setGeometry(QtCore.QRect(770, 60, 171, 201))
        self.tableGap5.setDragEnabled(False)
        self.tableGap5.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap5.setRowCount(6)
        self.tableGap5.setColumnCount(2)
        self.tableGap5.setObjectName("tableGap5")
        self.tableGap6 = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap6.setGeometry(QtCore.QRect(960, 60, 171, 201))
        self.tableGap6.setDragEnabled(False)
        self.tableGap6.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap6.setRowCount(6)
        self.tableGap6.setColumnCount(2)
        self.tableGap6.setObjectName("tableGap6")
        self.tableElong = QtWidgets.QTableWidget(self.tabGaps)
        self.tableElong.setGeometry(QtCore.QRect(1190, 60, 171, 201))
        self.tableElong.setDragEnabled(False)
        self.tableElong.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableElong.setRowCount(6)
        self.tableElong.setColumnCount(2)
        self.tableElong.setObjectName("tableElong")
        self.tableGap1_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap1_term.setGeometry(QtCore.QRect(20, 270, 171, 201))
        self.tableGap1_term.setDragEnabled(False)
        self.tableGap1_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap1_term.setRowCount(6)
        self.tableGap1_term.setColumnCount(2)
        self.tableGap1_term.setObjectName("tableGap1_term")
        self.tableGap5_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap5_term.setGeometry(QtCore.QRect(770, 270, 171, 201))
        self.tableGap5_term.setDragEnabled(False)
        self.tableGap5_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap5_term.setRowCount(6)
        self.tableGap5_term.setColumnCount(2)
        self.tableGap5_term.setObjectName("tableGap5_term")
        self.tableGap6_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap6_term.setGeometry(QtCore.QRect(960, 270, 171, 201))
        self.tableGap6_term.setDragEnabled(False)
        self.tableGap6_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap6_term.setRowCount(6)
        self.tableGap6_term.setColumnCount(2)
        self.tableGap6_term.setObjectName("tableGap6_term")
        self.tableGap3_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap3_term.setGeometry(QtCore.QRect(390, 270, 171, 201))
        self.tableGap3_term.setDragEnabled(False)
        self.tableGap3_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap3_term.setRowCount(6)
        self.tableGap3_term.setColumnCount(2)
        self.tableGap3_term.setObjectName("tableGap3_term")
        self.tableGap4_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap4_term.setGeometry(QtCore.QRect(580, 270, 171, 201))
        self.tableGap4_term.setDragEnabled(False)
        self.tableGap4_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap4_term.setRowCount(6)
        self.tableGap4_term.setColumnCount(2)
        self.tableGap4_term.setObjectName("tableGap4_term")
        self.tableGap2_term = QtWidgets.QTableWidget(self.tabGaps)
        self.tableGap2_term.setGeometry(QtCore.QRect(200, 270, 171, 201))
        self.tableGap2_term.setDragEnabled(False)
        self.tableGap2_term.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableGap2_term.setRowCount(6)
        self.tableGap2_term.setColumnCount(2)
        self.tableGap2_term.setObjectName("tableGap2_term")
        self.tabWidgetInput.addTab(self.tabGaps, "")
        self.tabDensities = QtWidgets.QWidget()
        self.tabDensities.setObjectName("tabDensities")
        self.tableCurrents_4 = QtWidgets.QTableWidget(self.tabDensities)
        self.tableCurrents_4.setGeometry(QtCore.QRect(50, 130, 1451, 641))
        self.tableCurrents_4.setDragEnabled(False)
        self.tableCurrents_4.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableCurrents_4.setRowCount(15)
        self.tableCurrents_4.setColumnCount(10)
        self.tableCurrents_4.setObjectName("tableCurrents_4")
        self.tabWidgetInput.addTab(self.tabDensities, "")
        self.tabHeating = QtWidgets.QWidget()
        self.tabHeating.setObjectName("tabHeating")
        self.tableCurrents_5 = QtWidgets.QTableWidget(self.tabHeating)
        self.tableCurrents_5.setGeometry(QtCore.QRect(20, 120, 1451, 641))
        self.tableCurrents_5.setDragEnabled(False)
        self.tableCurrents_5.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableCurrents_5.setRowCount(15)
        self.tableCurrents_5.setColumnCount(10)
        self.tableCurrents_5.setObjectName("tableCurrents_5")
        self.tabWidgetInput.addTab(self.tabHeating, "")
        self.tabControl = QtWidgets.QWidget()
        self.tabControl.setObjectName("tabControl")
        self.tableControlMarg = QtWidgets.QTableWidget(self.tabControl)
        self.tableControlMarg.setGeometry(QtCore.QRect(60, 50, 291, 531))
        self.tableControlMarg.setDragEnabled(False)
        self.tableControlMarg.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableControlMarg.setRowCount(13)
        self.tableControlMarg.setColumnCount(2)
        self.tableControlMarg.setObjectName("tableControlMarg")
        self.tableControl1 = QtWidgets.QTableWidget(self.tabControl)
        self.tableControl1.setGeometry(QtCore.QRect(420, 50, 171, 241))
        self.tableControl1.setDragEnabled(False)
        self.tableControl1.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableControl1.setRowCount(6)
        self.tableControl1.setColumnCount(1)
        self.tableControl1.setObjectName("tableControl1")
        self.tableControl1.horizontalHeader().setVisible(False)
        self.tableControl2 = QtWidgets.QTableWidget(self.tabControl)
        self.tableControl2.setGeometry(QtCore.QRect(660, 50, 171, 311))
        self.tableControl2.setDragEnabled(False)
        self.tableControl2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableControl2.setRowCount(7)
        self.tableControl2.setColumnCount(1)
        self.tableControl2.setObjectName("tableControl2")
        self.tableControl2.horizontalHeader().setVisible(False)
        self.tabWidgetInput.addTab(self.tabControl, "")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tabInput)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 410, 141))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layoutInputSetup = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layoutInputSetup.setContentsMargins(0, 0, 0, 0)
        self.layoutInputSetup.setObjectName("layoutInputSetup")
        self.btnBrowse = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnBrowse.setObjectName("btnBrowse")
        self.layoutInputSetup.addWidget(self.btnBrowse, 2, 0, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnSave.setObjectName("btnSave")
        self.layoutInputSetup.addWidget(self.btnSave, 2, 1, 1, 1)
        self.labelDir = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelDir.setObjectName("labelDir")
        self.layoutInputSetup.addWidget(self.labelDir, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabInput, "")
        self.tabOutput = QtWidgets.QWidget()
        self.tabOutput.setObjectName("tabOutput")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabOutput)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 221, 308))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnLoadIDS = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnLoadIDS.setObjectName("btnLoadIDS")
        self.gridLayout_2.addWidget(self.btnLoadIDS, 3, 1, 1, 1)
        self.labelRun = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelRun.setObjectName("labelRun")
        self.gridLayout_2.addWidget(self.labelRun, 1, 0, 1, 1)
        self.labelPulse = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelPulse.setObjectName("labelPulse")
        self.gridLayout_2.addWidget(self.labelPulse, 0, 0, 1, 1)
        self.textPulse = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textPulse.setObjectName("textPulse")
        self.gridLayout_2.addWidget(self.textPulse, 0, 1, 1, 1)
        self.textRun = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.textRun.setObjectName("textRun")
        self.gridLayout_2.addWidget(self.textRun, 1, 1, 1, 1)
        self.labelIDSInfo = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelIDSInfo.setText("")
        self.labelIDSInfo.setObjectName("labelIDSInfo")
        self.gridLayout_2.addWidget(self.labelIDSInfo, 3, 0, 1, 1)
        self.labelUser = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelUser.setObjectName("labelUser")
        self.gridLayout_2.addWidget(self.labelUser, 2, 0, 1, 1)
        self.textUser = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.textUser.setObjectName("textUser")
        self.gridLayout_2.addWidget(self.textUser, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tabOutput, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1624, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidgetInput.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DINA"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabCurrents), _translate("MainWindow", "Currents"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabVoltages), _translate("MainWindow", "Voltages"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabGaps), _translate("MainWindow", "Gaps"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabDensities), _translate("MainWindow", "Densities"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabHeating), _translate("MainWindow", "Heating"))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabControl), _translate("MainWindow", "Controller"))
        self.btnBrowse.setText(_translate("MainWindow", "Load from DINA work directory..."))
        self.btnSave.setText(_translate("MainWindow", "Save setups"))
        self.labelDir.setText(_translate("MainWindow", "Select DINA work directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInput), _translate("MainWindow", "Input"))
        self.btnLoadIDS.setText(_translate("MainWindow", "Load IDS"))
        self.labelRun.setText(_translate("MainWindow", "Run"))
        self.labelPulse.setText(_translate("MainWindow", "Pulse"))
        self.labelUser.setText(_translate("MainWindow", "User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOutput), _translate("MainWindow", "Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

