function CreateMex(MyPath)

if nargin == 1
    MyPath = [MyPath '/'];
else
    MyPath = '';
end

FFLAGS = ['FFLAGS=\$FFLAGS' ...
    ' -fPIC -fno-second-underscore -ffree-line-length-none' ...
    ' -I/work/imas/core/imas/3.6.0/ual/3.3.11/include/gfortran'];
LDFLAGS = ['LDFLAGS=\$LDFLAGS' ...
    ' -L/work/imas/core/imas/3.6.0/ual/3.3.11/lib -limas-gfortran'];

mex('-v', '-g', 'FC=gfortran', ...
    FFLAGS, ...
    'FOPTIMFLAGS=-O0', ...
    'FDEBUGFLAGS=-g', ...
    LDFLAGS, ...
    'LDOPTIMFLAGS= ',...
    'LDDEBUGFLAGS= ',...
    [MyPath 'mexLoadIDS.F90'], [MyPath 'mexFillIDSUtil.F90'], ...
    [MyPath 'mexFillEquilibrium.F90'], [MyPath 'mexFillPFActive.F90'], ...
    [MyPath 'mexFillPFPassive.F90'], [MyPath 'mexFillCoreProfiles.F90']);

end
