function CreateMex(MyPath)

if nargin == 1
    MyPath = [MyPath '/'];
else
    MyPath = '';
end

[status,imascflags] = system('pkg-config imas-gfortran --cflags');    
FFLAGS = ['FFLAGS=\$FFLAGS' ...
    ' -fPIC -fno-second-underscore -ffree-line-length-none ' deblank(imascflags)];
[status,imaslibs] = system('pkg-config imas-gfortran --libs');    
LDFLAGS = ['LDFLAGS=\$LDFLAGS ' deblank(imaslibs)];

mex('-v', '-g', 'FC=gfortran', ...
    FFLAGS, ...
    'FOPTIMFLAGS=-O0', ...
    'FDEBUGFLAGS=-g', ...
    LDFLAGS, ...
    'LDOPTIMFLAGS= ',...
    'LDDEBUGFLAGS= ',...
    [MyPath 'mexLoadIDS.F90'], [MyPath 'mexFillIDSUtil.F90'], ...
    [MyPath 'mexFillEquilibrium.F90'], [MyPath 'mexFillPFActive.F90'], ...
    [MyPath 'mexFillPFPassive.F90'], [MyPath 'mexFillCoreProfiles.F90']);

end
