c        PARAMETER ( nd=200, mu1=400, muh=400)
c        PARAMETER ( NR=90, NZ=90,nwnh=nr*nz, nwh=nz*nwnh, ngrid=196)

c  	PARAMETER ( nyz=2816)  !  33X90

  	PARAMETER ( nyz=7832)   !  90X90

c  	PARAMETER ( nyz=6952)   !  80X90


c  	PARAMETER ( nyz=270)   !  10X32


c  	PARAMETER ( nyz=10472)   !  120X90

c  	PARAMETER ( nyz=10502)   !  90X120

c  	PARAMETER ( nyz=5192)   !  60X90

c  	PARAMETER ( nyz=5270)   !  86X64









	 

